
name: Frontend CI

on: [push, pull_request]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install and build
        run: |
          cd frontend/web
          npm ci
          npm run build
